### ISSUE TITLE
Shared L3 Subnet will not synchronize to OpenStack

### ISSUE THREAD

**Issue by phantium** [nuagecommunity/nuage-amp#11]
Error:

```
2016-10-21 10:43:24,007:ERROR:nuage-amp:|- ERROR creating subnet: (ID:aead74da-c05a-4bca-87a1-511f4832f94f)
2016-10-21 10:43:24,007:ERROR:nuage-amp:BadRequest()
```

With line 156 in sync.py, the subnets value enable_dhcp should be True instead of False.

**Comment by dieterdm** [comment]
enable_dhcp should indeed be set to True. This also requires to set the network and subnet mask to the correct value. These values can be found in the SharedNetworkResource. However, this can lead to ip overlap if multiple OpenStack tenants sync the same shared subnet. The ideal solution would be the use of allocation_pools. This is unpractical, since the number of tenants and the size of the allocation pools cannot be known upfront. Another solution might be to leave the responsibility of avoiding ip overlap to the end user. An ip address can be chosen during port creation as follows:
`neutron port-create …. --fixed-ip ip_address=….`

**Comment by phantium** [comment]
Thanks for the fix @dieterdm 👍
